import { createTestDb } from '/home/user/TrueTCO/server/db/testing.ts';
const db = await createTestDb();
const t = await db.query(`SELECT count(*)::int n FROM information_schema.tables WHERE table_schema='public'`);
console.log('tables:', t[0].n);
const pol = await db.query(`SELECT count(*)::int n FROM pg_policies WHERE schemaname='public'`);
console.log('policies:', pol[0].n);
const rol = await db.query(`SELECT rolname, rolsuper FROM pg_roles WHERE rolname='truetco_app'`);
console.log('role:', JSON.stringify(rol));
const st = await db.status();
console.log('status:', JSON.stringify(st));
const mig = await db.query(`SELECT version, name FROM schema_migrations ORDER BY version`);
console.log('migrations:', JSON.stringify(mig));
await db.close();
